### ISSUE TITLE
Access to the path 'DeveloperImages\16.3' is denied

### ISSUE THREAD

**Issue by franky88j** [master131/iFakeLocation#128]
Hello,

Having an issue with my Iphone XS on 16.3.1

Developer mode is on. Phone is trusted on my windows 11 PC

Resulting in error:

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.UnauthorizedAccessException: Access to the path 'DeveloperImages\16.3' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at iFakeLocation.Program.DownloadState.ProcessNext()
   at iFakeLocation.Program.DownloadState.Start()
   at iFakeLocation.Program.HasDepedencies(HttpListenerContext ctx)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at iFakeLocation.Program.<>c__DisplayClass18_1.<Main>b__5(Object _)

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.UnauthorizedAccessException: Access to the path 'DeveloperImages\16.3' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at iFakeLocation.Program.DownloadState.ProcessNext()
   at iFakeLocation.Program.DownloadState.Start()
   at iFakeLocation.Program.HasDepedencies(HttpListenerContext ctx)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at iFakeLocation.Program.<>c__DisplayClass18_1.<Main>b__5(Object _)

**Comment by master131** [comment]
Have you tried running it as admin?

**Comment by franky88j** [comment]
How embarrasing, thank, you that fixed it !
