### ISSUE TITLE
Error setting fake location on iphone

### ISSUE THREAD

**Issue by rebelbeefcake** [master131/iFakeLocation#133]
I'm getting an error setting the location, I have developer mode on and restarted the phone multiple time. I tried to turn off the phone passcode and it is still the same issue.

I have used the app previously with no issues but I think this started after I updated to iso16.4.1 but can't be sure about that.

This is the error that appears in the windows when I press on the set fake location button. Hopefully someone will have an idea what it means and If I can fix it.

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.UnauthorizedAccessException: Access to the path 'DeveloperImages\16.4' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at iFakeLocation.Program.DownloadState.ProcessNext()
   at iFakeLocation.Program.DownloadState.Start()
   at iFakeLocation.Program.HasDepedencies(HttpListenerContext ctx)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at iFakeLocation.Program.<>c__DisplayClass18_1.<Main>b__5(Object _)

Any help would be appreciated

**Comment by master131** [comment]
Have you tried running the app as admin?

**Comment by rebelbeefcake** [comment]
I just tried that and it worked, thank you I appreciate your help.
