### ISSUE TITLE
Not working with iOS 12.3

### ISSUE THREAD

**Issue by Slugoid** [master131/iFakeLocation#2]
Getting these errors when running with iOS 12.3

`System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at iFakeLocation.Program.HasDepedencies(HttpListenerContext ctx)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at iFakeLocation.Program.<>c__DisplayClass16_1.<Main>b__5(Object _)`

**Comment by master131** [comment]
Apologies, that is a bug in the code which handles developer image depedencies. At this current time, iOS 12.3 is not supported as a developer image has not been supplied here:
https://github.com/xushuduo/Xcode-iOS-Developer-Disk-Image/tree/master/Developer%20Disk%20Image

**Comment by master131** [comment]
@Slugoid iOS 12.3 support has been fixed. Windows + Ubuntu versions available, macOS build will be available later today.

**Comment by mazicwong** [comment]
Problem likewise, Not working with IOS 12.1.
In mac, no feedback after clicking ''set fake location".
And in windows, it can be use normally. :)
