### ISSUE TITLE
Error to download 13.6

### ISSUE THREAD

**Issue by LeVuHoang** [master131/iFakeLocation#26]
Hi,

I redownloaded latest iFakeLocation and net core but the website is stuck at downloading 13.6.zip

When I executed the program in command line, I have this error
```
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'ICSharpCode.SharpZipLib, Version=1.2.0.246, Culture=neutral, PublicKeyToken=1b03e6acf1164f73'. The system cannot find the file specified.

   at iFakeLocation.Program.DeveloperImageZipDownloaded(Object sender, EventArgs e)
   at iFakeLocation.Program.DownloadState.WebClient_DownloadFileCompleted(Object sender, AsyncCompletedEventArgs e) in C:\Users\Tommy\Documents\Visual Studio 2015\Projects\iFakeLocation\iFakeLocation\Program.cs:line 176
   at System.Net.WebClient.OnDownloadFileCompleted(AsyncCompletedEventArgs e)
   at System.Net.WebClient.<StartAsyncOperation>b__78_4(Object arg)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
./iFakeLocation: line 4:  2241 Abort trap: 6           ./bin/main
```

Even I downloaded 13.6.zip and unzip to DeveloperImages, the website always downloads 13.6.zip

**Comment by LeVuHoang** [comment]
Got a message from master131:
1. Download 13.6.zip from
https://github.com/haikieu/xcode-developer-disk-image-all-platforms/tree/master/DiskImages/iPhoneOS.platform/DeviceSupport

2. Right-click on iFakeLocation.app, choose Show Package Content
3. Go to bin/DeveloperImages, unzip 13.6.zip

It should be good to go.
