### ISSUE TITLE
iFakeLocation crashes on macOS Catalina 10.15.6

### ISSUE THREAD

**Issue by ingenieurmt** [master131/iFakeLocation#29]
iFakeLocation crashes just prior to completing the download of the developer image.

```
iFakeLocation is now running at: http://localhost:49216/

Press Ctrl-C to quit (or click the close button).

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'ICSharpCode.SharpZipLib, Version=1.2.0.246, Culture=neutral, PublicKeyToken=1b03e6acf1164f73'. The system cannot find the file specified.

   at iFakeLocation.Program.DeveloperImageZipDownloaded(Object sender, EventArgs e)
   at iFakeLocation.Program.DownloadState.WebClient_DownloadFileCompleted(Object sender, AsyncCompletedEventArgs e) in C:\Users\Tommy\Documents\Visual Studio 2015\Projects\iFakeLocation\iFakeLocation\Program.cs:line 176
   at System.Net.WebClient.OnDownloadFileCompleted(AsyncCompletedEventArgs e)
   at System.Net.WebClient.<StartAsyncOperation>b__78_4(Object arg)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
./iFakeLocation: line 4:  6854 Abort trap: 6           ./bin/main
```

**Comment by master131** [comment]
Can you please try this version below and see if it works?

[ifakelocation-v1.4.1-macosx-x64-v3.zip](https://github.com/master131/iFakeLocation/files/5174086/ifakelocation-v1.4.1-macosx-x64-v3.zip)

**Comment by ingenieurmt** [comment]
@master131 Tested just now and looks like it works fine, I was able to download the dev image, set a location and stop it without issues.

**Comment by master131** [comment]
@ingenieurmt Thanks, I will update the main release. I know the macOS version has been broken for some time but I haven't had the time to fix it.
