### ISSUE TITLE
Unable to set fake location

### ISSUE THREAD

**Issue by kuro123456723456u** [master131/iFakeLocation#53]
So i connected my phone successfully to the macbook, and have entered the location then press search. But when I press "set fake location", the application takes a long time to set (the button never turn from light blue back into dark blue and the message that the fake location has been set successfully never came up) 
I have reset the application multiply times by deleting and re-downloading but the problem is still there. 
any help is appreciated thanks

**Comment by rwang301** [comment]
I am facing the same issue

**Comment by sdarmadi1106** [comment]
Same problem here. Anyone know how I can fix it? :(

iFakeLocation is now running at: http://localhost:49216/

Press Ctrl-C to quit (or click the close button).

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.IOException: Read-only file system
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at iFakeLocation.Program.DownloadState.ProcessNext() in C:\Users\Tommy\Documents\Visual Studio 2015\Projects\iFakeLocation\iFakeLocation\Program.cs:line 192
   at iFakeLocation.Program.DownloadState.Start() in C:\Users\Tommy\Documents\Visual Studio 2015\Projects\iFakeLocation\iFakeLocation\Program.cs:line 198
   at iFakeLocation.Program.HasDepedencies(HttpListenerContext ctx) in C:\Users\Tommy\Documents\Visual Studio 2015\Projects\iFakeLocation\iFakeLocation\Program.cs:line 373
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at iFakeLocation.Program.<>c__DisplayClass18_1.<Main>b__5(Object _) in C:\Users\Tommy\Documents\Visual Studio 2015\Projects\iFakeLocation\iFakeLocation\Program.cs:line 458

**Comment by master131** [comment]
Please confirm what OS is being used. Also make sure you are running iFakeLocation from somewhere like your Desktop which has normal write access.

**Comment by MURADSAYYAD000** [comment]
Please tell me me how to set fake location in Android. Without using pc

**Comment by bgktmxg** [comment]
> Please tell me me how to set fake location in Android. Without using pc.

This software is iOS devices and only and requires a PC or a mac
